fix: hide credential logs when disconnectiong from db server
guidesmiths/systemic-mongodb pull request #21
Opened 2021-09-02 08:01 UTC by hamsaaldrobi

2021-09-02 08:23 UTC, kevinccbsg requested changes

2021-09-02 08:23 UTC, kevinccbsg commented on index.js
> +    }
```suggestion
    if(config.showConnectionString){
      logger.info(`Disconnecting from ${config.url}`);
    } else {
      logger.info(`Disconnecting from server <hidden connection url>`);
    }
```

2021-09-02 08:40 UTC, kevinccbsg approved these changes

2021-09-02 08:43 UTC, UlisesGascon approved these changes
LGTM! 🚀

2021-09-02 09:19 UTC, Betisman commented on index.js
> +    }
```suggestion
    if (config.showConnectionString) {
      logger.info(`Disconnecting from ${config.url}`);
    } else {
      logger.info(`Disconnecting from server <hidden connection url>`);
    }
```

2021-09-14 07:00 UTC, MatteoDiPaolo approved these changes
LGTM

2021-09-14 07:01 UTC, merged